# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: actions/checkout@v2
        uses: actions/checkout@v2
        with:
          path: develop

      - name: deploy action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /home/visiiime-dock
            docker-compose exec -T --user=laradock workspace bash -c "cd /var/www/visiiime;git checkout develop"
            docker-compose exec -T --user=laradock workspace bash -c "cd /var/www/visiiime;git pull"
            docker-compose exec -T --user=laradock workspace bash -c "cd /var/www/visiiime;composer dumpautoload"
            docker-compose exec -T --user=laradock workspace bash -c "cd /var/www/visiiime;php artisan config:clear"
            docker-compose exec -T --user=laradock workspace bash -c "cd /var/www/visiiime;php artisan cache:clear"
            docker-compose exec -T --user=laradock workspace bash -c "cd /var/www/visiiime;php artisan config:cache"
            curl -X POST https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_IDENTIFIER }}/purge_cache \
              -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_TOKEN }}" \
              -H "Content-Type: application/json" \
              --data '{"files":["https://dev-web.visiiime.com/js"]}'
