# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: actions/checkout@v2
        uses: actions/checkout@v2
        with:
          path: develop

      - name: deploy action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /home/laradock
            docker-compose exec --user=laradock workspace bash
            ls
            # cd visiiime
            # git checkout develop
            # git pull
            # composer dumpautoload
            # php artisan config:clear
            # php artisan cache:clear
            # php artisan config:cache


